# fly.toml file generated for gotify-server on 2023-04-11T09:53:11+07:00

app = "gotify-server"
primary_region = "sin"

[env]
  DB_REPLICA_URL = "s3://sqlite-snapshot/gotify"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  [http_service.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"